# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Blog | btwoa
subtitle: '放养平凡'
description: '我仍相信人间滚烫'
keywords: 编程，安全, 生活
author: btwoa
language: zh-CN
timezone: 'Asia/Macau'

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://blog.btwoa.com
permalink: :abbrlink/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - random/index.html
  - sticker.json
  - friends.json
  - robots.txt
  - 404.html

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
  优化风格: Optimized Style
  重申许可: Renew License
  搭建博客: Create Blog
  警告信息: Warning Message
  实用资源: Practical Resource
  刷题笔记: Take Notes
  知识总结: Knowledge Summary
  游戏教程: Game Tutorial
  无问西东: Forever Young
  完美刷机: Perfect Brush
  完美编译: Compiles Perfectly
  案件转区: Transforms The Region
  免费域名: Free Domain
  域名邮箱: Domain Email
  环境变量: Environment Variable
tag_map: 
  插件: Plugins
  编码: Encode
  正则: Regular
  比较: Comparisons
  绕过: Bypass
  注入: Injection
  自定义: Custom

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
Plugins:
  - hexo-abbrlink
  - hexo-blog-encrypt
  - hexo-filter-links
  - hexo-generator-archive
  - hexo-generator-sitemap
  - hexo-generator-feed
  - hexo-hide-posts
  - hexo-minify
  - hexo-next-pwa
  - hexo-renderer-marked
  - hexo-sliding-spoiler 

abbrlink:
  alg: crc32
  rep: hex
  drafts: false
  auto_category:
     enable: true  
     depth: 3
     over_write: false 
  auto_title: false
  auto_date: false
  force: false

encrypt: 
  abstract: 此文章已加密, 请输入密码查看
  message: 在此输入密码
  wrong_pass_message: 密码错误, 请重新输入
  wrong_hash_message: 此文章不能被校验, 但可以查看解密后的内容

links:
  enable: false
  field: 'site'
  exclude:
    - 'btwoa.com'
    - 'game.btwoa.com'    
    - 'gallery.btwoa.com'

archive_generator:
  enabled: true
  per_page: 0
  yearly: true
  monthly: false
  daily: false
  order_by: -date

sitemap:
    path: sitemap.xml

feed:
  type: 
    - atom
    - rss2
  path: 
    - atom.xml
    - rss.xml 
  limit: false 
  hub:
  content: fales
  content_limit: 140 
  content_limit_delim: ' ' 
  order_by: -date
  icon: https://ovo.btwoa.com/favicon/hexo/favicon.png

hide_posts:
  enable: true
  filter: hidden
  public_generators: [sitemap]
  noindex: false

## Hexo-minify Default Config Options
minify:
  js:
    enable: false
    options:
  css:
    enable: true
    options:
  html:
    enable: true
    options: 
      minifyJS: true
      minifyCSS: true
      removeComments: false
      collapseWhitespace: true
      removeAttributeQuotes: true
  postcss:
    enable: true
    options: 
      # JavaScript 数组写法
      # overrideBrowserslist: ['> 1%', 'last 2 versions', 'not dead']
      # YAML 数组写法
      overrideBrowserslist: 
        - '> 1%'
        - last 2 versions
        - not dead

pwa:
  manifest:
    path: /manifest.json
    body:
      name: Blog
      short_name: btwoa
      lang: zh-CN
      display: standalone
      background_color: "#ffffff"
      theme_color: "#ffffff"
      icons:
        - src: https://ovo.btwoa.com/favicon/hexo/favicon32.png
          sizes: 32x32
          type: image/png
        - src: https://ovo.btwoa.com/favicon/hexo/favicon48.png
          sizes: 48x48
          type: image/png
        - src: https://ovo.btwoa.com/favicon/hexo/favicon72.png
          sizes: 72x72
          type: image/png
        - src: https://ovo.btwoa.com/favicon/hexo/favicon96.png
          sizes: 96x96
          type: image/png
        - src: https://ovo.btwoa.com/favicon/hexo/favicon144.png
          sizes: 144x144
          type: image/png
        - src: https://ovo.btwoa.com/favicon/hexo/favicon168.png
          sizes: 168x168
          type: image/png
        - src: https://ovo.btwoa.com/favicon/hexo/favicon192.png
          sizes: 192x192
          type: image/png
        - src: https://ovo.btwoa.com/favicon/hexo/favicon256.png
          sizes: 256x256
          type: image/png
        - src: https://ovo.btwoa.com/favicon/hexo/favicon512.png
          sizes: 512x512
          type: image/png
    serviceWorker:
    options:
      offlineGoogleAnalytics: true

marked:
  gfm: true
  pedantic: false
  breaks: true
  smartLists: true
  smartypants: true
  quotes: '“”‘’'
  modifyAnchors: 0
  anchorAlias: false
  autolink: true
  mangle: true
  sanitizeUrl: false
  dompurify: false
  headerIds: true
  lazyload: false
  prependRoot: true
  postAsset: false
  external_link:
    enable: false
    exclude: []
    nofollow: false
  disableNunjucks: false
  descriptionLists: true

## Themes: https://hexo.io/themes/
theme: apollo

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
    type: git
    repo: https://github.com/btwoa/hexo.git
    branch: main